version: '3.8'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "27362:8000"
    volumes:
      - ./app:/app/app
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=requests
      - USE_CUDA=1  # Установите 1, если хотите использовать GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - qdrant
    restart: always
    command: >
      sh -c "
        uv run python wait-for-it.py &&
        uv run uvicorn main:app --host 0.0.0.0 --port 8000
      "


  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: always

  streamlit:
    image: python:3.9-slim
    ports:
      - "27363:8501"
    volumes:
      - ./forntend:/app  # Монтирование всей директории
    working_dir: /app
    environment:
      API_URL: "http://api:8000"
    command: >
      sh -c "
        pip install --no-cache-dir streamlit pandas seaborn matplotlib requests scikit-learn tqdm openpyxl xlrd &&
        ls
        streamlit run main.py \
          --server.port=8501 \
          --server.fileWatcherType none
      "

volumes:
  qdrant_data: